# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.11"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  date_format:
    dependency: "direct main"
    description:
      name: date_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  date_utils:
    dependency: "direct main"
    description:
      name: date_utils
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.18"
  firebase_core:
    dependency: transitive
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_billing:
    dependency: "direct main"
    description:
      name: flutter_billing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
  flutter_facebook_login:
    dependency: "direct main"
    description:
      name: flutter_facebook_login
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  flutter_inapp_purchase:
    dependency: "direct main"
    description